platform :ios, '8.0'
use_frameworks!

target 'M7AutoTracker_Example' do
  pod 'M7AutoTracker', :path => '../'

  target 'M7AutoTracker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
    # Swift 版本声明
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        if ['FBSnapshotTestCase'].include? target.name
          target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
          end
          else
          target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
          end
        end
      end
    end
  end
  

end
